#!/usr/bin/env node

import { program } from 'commander';
import figlet from 'figlet';
import mainPrompt from './prompts/main.prompt.js';
import downloadCourseVideos from './utils/download.js';

const banner = figlet.textSync('Plural Ripper', {
    font: 'Standard',
    horizontalLayout: 'default',
    verticalLayout: 'default',
    width: 80,
    whitespaceBreak: true,
});
console.log(banner);

interface Options {
    json: string;
    output: string;
}

program.version('0.2.0');
program
    .option(
        '-j, --json <json>',
        'JSON file path generated by instruction from https://github.com/sayeed205/plural-ripper'
    )
    .option('-o, --output <output>', 'Output directory path')
    .description('Download courses from https://pluralsight.com/')
    .action((options: Options) => {
        const { json, output } = options;
        downloadCourseVideos(json, output);
    });

if (process.argv.length > 2) {
    program.parse(process.argv);
} else {
    mainPrompt();
}
